### ISSUE TITLE
Documentos de elicitação

### ISSUE THREAD

**Issue by brendavsantos** [Requisitos-de-Software/2020.2-Telegram#7]
## Descrição
Criação e desenvolvimento dos documentos de elicitação.

## Tarefas
- [x] [Brainstorming](https://github.com/Requisitos-de-Software/2020.2-Telegram/issues/13)
- [x] [Observação](https://github.com/Requisitos-de-Software/2020.2-Telegram/issues/9)
- [x] [Storytelling](https://github.com/Requisitos-de-Software/2020.2-Telegram/issues/8)
- [x] [Entrevista](https://github.com/Requisitos-de-Software/2020.2-Telegram/issues/23)
- [x] [Análise de Protocolo](https://github.com/Requisitos-de-Software/2020.2-Telegram/issues/20)
- [x] [Análise de Discurso](https://github.com/Requisitos-de-Software/2020.2-Telegram/issues/10)
- [x] [Questionário](https://github.com/Requisitos-de-Software/2020.2-Telegram/issues/16)
- [x] [Instrospecção](https://github.com/Requisitos-de-Software/2020.2-Telegram/issues/12)

## Critérios de Aceitação
- [x] Todos os documentos estarem completos
- [x] Todos os documentos serem revisados

**Comment by lboaventura25** [comment]
Não se esqueçam de criar a issue pra cada técnica de elicitação, como está em #8 e conectar aqui na issue principal.
